spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chess_stats
    username: chess
    password: chess

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: 8080